# Generated by Django 5.2.13 on 2026-04-11 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion_texto', models.CharField(max_length=300)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('capacidad_max', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField()),
                ('host', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('declined', 'Rechazado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='fiestas_core.fiesta')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fiesta', 'estado'], name='fiestas_cor_fiesta__289b2e_idx')],
            },
        ),
    ]
