CREATE TABLE guide (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    zone VARCHAR(255) NOT NULL,
    experience INT DEFAULT 0,
    active BOOLEAN DEFAULT TRUE
);
